name: Maven - Generate and publish releases with SBOM

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version to build with"
        type: string
        default: "25"
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  release-sbom:
    name: Generate and publish release with SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09  # v5
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      - name: Install Snyk CLI
        uses: snyk/actions/setup@12140f4059e244892ae643824a95459a102120dd

      - name: Create SBOM
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: ${{ vars.SNYK_API }}
          SNYK_ORG: ${{ vars.SNYK_ORG }}
        run: |
          snyk sbom --format=cyclonedx1.6+json \
                    --maven-aggregate-project \
                    --maven-skip-wrapper \
                    --json-file-output=sbom.cdx.json

      - name: Upload SBOM to release assets
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            sbom.cdx.json \
            --verify-tag \
            --title "$TAG"
