# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and test

on:
  workflow_call:
    inputs:
      debug:
        description: "Whether to build artifacts for normal development and debugging (default: true)"
        type: boolean
        required: false
        default: true
      release:
        description: "Whether to also build artifacts in release mode, with optimizations"
        type: boolean
        required: false
        default: false

permissions:
  # to fetch code (actions/checkout)
  contents: read
  # https://github.com/marketplace/actions/publish-test-results#permissions
  # https://github.com/marketplace/actions/junit-report-action
  checks: write
  pull-requests: write # only required if `comment: true` was enabled

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://doc.rust-lang.org/cargo/reference/profiles.html:
        # Cargo has 4 built-in profiles: dev, release, test, and bench
        BUILD_TARGET: [ dev, release ] # refers to a cargo profile
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Build binaries (${{ matrix.BUILD_TARGET }})
        # Rust available from the get go in ubuntu-latest (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#rust-tools)
        if: ${{ (inputs.debug && (matrix.BUILD_TARGET == 'dev')) || (inputs.release && (matrix.BUILD_TARGET == 'release')) }}
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
        continue-on-error: false

      - name: Run tests (${{ matrix.BUILD_TARGET }})
        if: ${{ (inputs.debug && (matrix.BUILD_TARGET == 'dev')) || (inputs.release && (matrix.BUILD_TARGET == 'release')) }}
        # as suggested by https://github.com/johnterickson/cargo2junit
        run: |
          cargo install cargo2junit
          cargo test --profile ${{ matrix.BUILD_TARGET }} -- -Z unstable-options --format json --report-time | tee test-results-${{ matrix.BUILD_TARGET }}.json
          cat test-results-${{ matrix.BUILD_TARGET }}.json | cargo2junit > test-results-${{ matrix.BUILD_TARGET }}.xml
        env: # See https://github.com/johnterickson/cargo2junit/issues/79
          RUSTC_BOOTSTRAP: 1
        #continue-on-error: false

      - name: Upload test results (${{ matrix.BUILD_TARGET }})
        if: (!cancelled())
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Test results (${{ matrix.BUILD_TARGET }})
          path: test-results-${{ matrix.BUILD_TARGET }}.xml
          retention-days: 1 # minimum

  # as suggested by https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#use-with-matrix-strategy
  publish-test-results:
    name: Publish tests results
    needs: build-and-test
    runs-on: ubuntu-latest
    if: (!cancelled())

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        with:
          files: artifacts/**/test-results-*.xml
          deduplicate_classes_by_file_name: true
          report_individual_runs: true
