zenuml
    title Rust Clippy Workflow

    @Actor Dev
    @GitHub GitHub
    @Kubernetes "rust-toolchain@linux"
    @LogicApps CodeQL

    // 1. By running:<br> `git comit -am ... && git push`
    Dev->GitHub."push local commits to remote" {
        // 2. ⚠️ **Only in case any of `**/*rs` changed**
        GitHub->"rust-toolchain@linux"."run Clippy" {
            // 3. (previously converted from<br> the _Clippy_ output)
            "rust-toolchain@linux"->CodeQL."upload SARIF file" {
                CodeQL:"scan the SARIF file against vulnerabilities"
                opt {
                    // 3. Create alert(s)<br> (browsable via _Security -> Code scanning_)<br> based on the vulnerabilities report
                    CodeQL->GitHub:"raise alerts"
                        // 4. ⚠️ **Only if _Watch "Security alerts"_ option activated:**<br> Send an email notification<br> featuring a detailed report<br> on all new security issues
                        GitHub->Dev:notify
                    }
                }
            }
        }
